/* AUTOGENERATED DO NOT MODIFY */

/**
  ******************************************************************************
  * @file    cenk.c
  * @brief   NN Code autogenerated DO NOT MODIFY IT
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/*
 * GIT_SHA         "6770925d2803cfc24528c45bb3ba8b791b2a83e4"
 * GIT_BRANCH      "STAI-4.0"
 * GIT_DESCRIPTION "atonn-v1.1.3-275-g6770925d"
 *
 * Command Line options:
 * --load-mdesc-file = "/opt/ST/STEdgeAI/4.0/Utilities/configs/stm32n6"
 * --load-cdesc-file = "/opt/ST/STEdgeAI/4.0/Utilities/configs/cortex-m55"
 * --load-mpool-file = "/home/ck/stm32ai-modelzoo-services/application_code/image_classification/STM32N6/Model/my_mpools/cenk"
 * --cache-maintenance = true
 * --enable-virtual-mem-pools = true
 * --native-float = true
 * --json-quant-file = "/home/ck/stm32ai-modelzoo-services/image_classification/cenk_generated/cenk_classifier_int8_OE_3_3_1_Q.json"
 * --optimization = 3
 * --Os = true
 * --Omax-ca-pipe = 4
 * --Ocache-opt = true
 * --enable-epoch-controller = true
 * --output-info-file = "c_info"
 * --onnx-input = "/home/ck/stm32ai-modelzoo-services/image_classification/cenk_generated/cenk_classifier_int8_OE_3_3_1.onnx"
 * --out-dir-prefix = "/home/ck/stm32ai-modelzoo-services/image_classification/cenk_generated/neural_art__cenk/"
 * --network-name = "cenk"
 * --all-buffers-info = true
 * --generate-stai = true
 * --Oauto-sched = true
 *
 * auto* option expanded into:
 *   alt-scheduler = false
 */

#include "ll_aton_NN_interface.h"
#include "ll_aton.h"
#include "ll_aton_lib.h"
#include "ll_aton_version.h"
#include "ll_sw.h"
#include "ecloader.h"
#include "ll_aton_cipher.h"

#if LL_ATON_VERSION_MAJOR != 1 || LL_ATON_VERSION_MINOR != 1 || LL_ATON_VERSION_MICRO != 3 || LL_ATON_VERSION_DEV != 275
#  error "Possible mismatch in ll_aton library used"
#endif

#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#  define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

/* global pool 8 is 25.00 KB */
/* index=8 file postfix=xSPI2 name=octoFlash offset=0x70400000  absolute_mode size=16777208 READ_ONLY THROUGHPUT=MID LATENCY=HIGH byte width=1 freq ratio=6 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=ON read_power=110 write_power=400 use4initializers=YES score=50  */
/* global pool 7 is ? */
/* index=7 file postfix=xSPI1 name=hyperRAM offset=0x90000000  absolute_mode size=16777208 READ_WRITE THROUGHPUT=MID LATENCY=HIGH byte width=2 freq ratio=5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=ON read_power=380 write_power=340 use4initializers=YES score=82  */
/* global pool 1 is 85.75 KB */
/* index=1 file postfix=AXISRAM5 name=npuRAM5 offset=0x342e0000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 2 is ? */
/* index=2 file postfix=AXISRAM4 name=npuRAM4 offset=0x34270000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 3 is ? */
/* index=3 file postfix=AXISRAM3 name=npuRAM3 offset=0x34200000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 0 is ? */
/* index=0 file postfix=AXISRAM6 name=npuRAM6 offset=0x34350000  absolute_mode size=458744 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=19.006 write_power=15.79 use4initializers=NO score=94  */
/* global pool 11 is 1.96 MB */
/* index=11 file postfix=AXISRAM2_AXISRAM3_AXISRAM4_AXISRAM5_AXISRAM6 name=cpuRAM2_npuRAM3_npuRAM4_npuRAM5_npuRAM6 offset=0x34100000  absolute_mode size=2883576 vpool READ_WRITE THROUGHPUT=HIGH LATENCY=MID byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=19.006 write_power=16.201 use4initializers=NO score=91  */
/* global pool 4 is ? */
/* index=4 file postfix=AXISRAM2 name=cpuRAM2 offset=0x34100000  absolute_mode size=1048576 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=17.324 write_power=15.321 use4initializers=NO score=84  */
/* global pool 5 is ? */
/* index=5 file postfix=AXISRAM1 name=cpuRAM1 offset=0x34080000  absolute_mode size=0 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=16.616 write_power=14.522 use4initializers=NO score=84  */
/* global pool 6 is ? */
/* index=6 file postfix=AXIFLEXMEM name=flexMEM offset=0x34000000  absolute_mode size=0 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=9.381 write_power=8.569 use4initializers=NO score=84  */


const LL_Streng_EncryptionTypedef *LL_ATON_WeightEncryption_Info_cenk()
{
  static const LL_Streng_EncryptionTypedef LL_Streng_EncryptionStruct = {
    .enable = 0,
  };

  return &LL_Streng_EncryptionStruct;
}

const LL_Streng_EncryptionTypedef *LL_ATON_BlobEncryption_Info_cenk()
{
  static const LL_Streng_EncryptionTypedef LL_Streng_EncryptionStruct = {
    .enable = 0,
  };

  return &LL_Streng_EncryptionStruct;
}

LL_ATON_User_IO_Result_t LL_ATON_Set_User_Input_Buffer_cenk(uint32_t num, void* buffer, uint32_t size)
{
  LL_ATON_LIB_UNUSED(num);
  LL_ATON_LIB_UNUSED(buffer);
  LL_ATON_LIB_UNUSED(size);

  { 
    return LL_ATON_User_IO_WRONG_INDEX;
  }
}

void *LL_ATON_Get_User_Input_Buffer_cenk(uint32_t num)
{
  LL_ATON_LIB_UNUSED(num);

  { 
    return NULL;
  }
}

LL_ATON_User_IO_Result_t LL_ATON_Set_User_Output_Buffer_cenk(uint32_t num, void* buffer, uint32_t size)
{
  LL_ATON_LIB_UNUSED(num);
  LL_ATON_LIB_UNUSED(buffer);
  LL_ATON_LIB_UNUSED(size);

  { 
    return LL_ATON_User_IO_WRONG_INDEX;
  }
}

void *LL_ATON_Get_User_Output_Buffer_cenk(uint32_t num)
{
  LL_ATON_LIB_UNUSED(num);

  { 
    return NULL;
  }
}

#include "cenk_ecblobs.h"

/* scheduling epoch=0    nodes=26  ------------------------------------------------------------------- */

// Epoch Controller Blob (name='_ec_blob_cenk_1') micro instructions needed

// Epoch Controller Blob (name='_ec_blob_cenk_1') start function
static void _ec_blob_cache_start_func_1(const LL_ATON_RT_EpochBlockItem_t *epoch_block, const NN_Instance_TypeDef *nn_instance) {
  LL_ATON_LIB_UNUSED(epoch_block);
  LL_ATON_LIB_UNUSED(nn_instance);

  /* *** MCU cache invalidate (only) operation (HW, whole range) *** */
  /*     memory pool: 1 */
  /*     start: ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 75360))) */
  /*     end:   ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 75392))) */
  LL_ATON_Cache_MCU_Invalidate_Range(((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 75360))) /* Equivalent hex address = 0x342f2660UL */, 32);

};


/* scheduling epoch=8    nodes=1   ------------------------------------------------------------------- */


static void LL_ATON_End_EpochBlock_8(const LL_ATON_RT_EpochBlockItem_t *epoch_block, const NN_Instance_TypeDef *nn_instance)
{
  LL_ATON_LIB_UNUSED(epoch_block);
  LL_ATON_LIB_UNUSED(nn_instance);

  /* *** MCU cache invalidate (only) operation for unaligned buffer start or end address (only line) *** */
  /*     memory pool: 1 */
  /*     start: ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 0))) */
  /*     end:   ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 32))) */
  LL_ATON_Cache_MCU_Invalidate_Range(((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 0))) /* Equivalent hex address = 0x342e0000UL */, 32);


/* Unit= 27 [PROCESSOR 0] */
/* kind=DequantizeLinear node=Dequantize_35 */
  Dequantizelinear_sw_info dequantizelinear1_sw_info = {
    /* "general.input" tensor-related info: */
    .general.input.dim.tensor_b = 1,
    .general.input.dim.tensor_h = 1,
    .general.input.dim.tensor_w = 1,
    .general.input.dim.tensor_c = 1,
    .general.input.dim.num_elem = 1,
    .general.input.stride.b = 1,
    .general.input.stride.h = 1,
    .general.input.stride.w = 1,
    .general.input.stride.c = 1,
    .general.input.mem.start_offset = ((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 75360))) /* Equivalent hex address = 0x342f2660UL */,
    .general.input.format.is_signed = 1,
    /* "is" tensor-related info: */
    .is.mem.start_offset = ((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x70400000UL + 25584))) /* Equivalent hex address = 0x704063f0UL */,
    .is.format.is_signed = 1,
    .is.dim.num_elem = 1,
    /* "izp" tensor-related info: */
    .izp.mem.start_offset = ((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x70400000UL + 25600))) /* Equivalent hex address = 0x70406400UL */,
    .izp.format.is_signed = 1,
    .izp.dim.num_elem = 1,
    /* "general.output" tensor-related info: */
    .general.output.dim.tensor_b = 1,
    .general.output.dim.tensor_h = 1,
    .general.output.dim.tensor_w = 1,
    .general.output.dim.tensor_c = 1,
    .general.output.dim.num_elem = 1,
    .general.output.stride.b = 4,
    .general.output.stride.h = 4,
    .general.output.stride.w = 4,
    .general.output.stride.c = 4,
    .general.output.mem.start_offset = ((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 0))) /* Equivalent hex address = 0x342e0000UL */,
    .general.output.format.is_signed = 1,
    .general.type = LL_SW_DEQUANTIZELINEAR,
  };

  /* Low Level SW Layer function invocation. This will exploit EmbedNets libs) */
  /* Node Dequantize_35 mapped on EmbedNets (INTEGER) as DequantizeLinear | Category: Format-Converter */
  ll_sw_forward_dequantizelinear(&dequantizelinear1_sw_info);
  /* *** MCU cache clean (only) operation (SW, whole range) *** */
  /*     memory pool: 1 */
  /*     start: ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 0))) */
  /*     end:   ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 32))) */
  LL_ATON_Cache_MCU_Clean_Range(((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 0))) /* Equivalent hex address = 0x342e0000UL */, 32);


}

/* scheduling epoch=9    nodes=1   ------------------------------------------------------------------- */

/* scheduling DONE                 ------------------------------------------------------------------- */

const LL_ATON_RT_EpochBlockItem_t *LL_ATON_EpochBlockItems_cenk(void) {

  static const LL_ATON_RT_EpochBlockItem_t ll_atonn_rt_epoch_block_array[] = {
    {
      .start_epoch_block = _ec_blob_cache_start_func_1,
      .end_epoch_block = NULL,
      .blob_address = (uintptr_t)(_ec_blob_cenk_1_address),
      .wait_mask = 0,
      .flags = EpochBlock_Flags_epoch_start | EpochBlock_Flags_epoch_end | EpochBlock_Flags_blob | EpochBlock_Flags_pure_hw,
#ifdef LL_ATON_EB_DBG_INFO
      .epoch_num = 1,
      .last_epoch_num = 7,
      .estimated_npu_cycles = 389558,
      .estimated_tot_cycles = 461760,
#endif // LL_ATON_EB_DBG_INFO
    },
    {
      .start_epoch_block = NULL,
      .end_epoch_block = LL_ATON_End_EpochBlock_8,
      .wait_mask = 0x00000000,
      .flags = EpochBlock_Flags_epoch_start | EpochBlock_Flags_epoch_end | EpochBlock_Flags_pure_sw,
#ifdef LL_ATON_EB_DBG_INFO
      .epoch_num = 8,
      .last_epoch_num = 8,
      .in_streng_mask = 0x00000000,
      .out_streng_mask = 0x00000000,
      .estimated_npu_cycles = 4,
      .estimated_tot_cycles = 30,
#endif // LL_ATON_EB_DBG_INFO
    },
    {
      .flags = EpochBlock_Flags_last_eb,
    },
  };


  return ll_atonn_rt_epoch_block_array;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Input_Buffers_Info_cenk(void)
{
  static const uint32_t buff_info__shape_1_112_112_3[] = { 1, 112, 3, 112 };
  static const uint32_t buff_info__mem_shape_F_1_112_112_3[] = { 1, 112, 112, 3 };
  static const float buff_info_Input_0_out_0_quant_scale[] = { 1 };
  static const int16_t buff_info_Input_0_out_0_quant_offset[] = { 0 };
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
  static const uint32_t buff_info__shape_16_3_3_3[] = { 16, 3, 3, 3 };
  static const uint32_t buff_info__mem_shape_L_16_3_3_3[] = { 16, 3, 3, 3 };
  static const float buff_info_Conv2D_7_weights_quant_scale[] = { 7.20927891961765e-06, 6.61777085042559e-06, 5.99253053223947e-06, 9.4148581410991e-06, 5.14917974214768e-06, 6.05505692874431e-06, 6.26388600721839e-06, 5.75314197703847e-06, 9.03492400539108e-06, 6.46077342025819e-06, 6.60474370306474e-06, 5.49613287148532e-06, 5.50784534425475e-06, 6.65459765514242e-06, 6.04671458859229e-06, 5.90757781537832e-06 };
  static const int16_t buff_info_Conv2D_7_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_32_16_3_3[] = { 32, 3, 3, 16 };
  static const uint32_t buff_info__mem_shape_M8_32_16_3_3[] = { 32, 2, 3, 3, 8 };
  static const float buff_info_Conv2D_13_weights_quant_scale[] = { 0.00340545317158103, 0.00207994366064668, 0.00125253957230598, 0.00369354547001421, 0.00197179964743555, 0.00210126489400864, 0.00150797353126109, 0.00196072109974921, 0.00183571700472385, 0.00227534840814769, 0.00276370951905847, 0.0020777159370482, 0.00258423248305917, 0.00147059408482164, 0.00215832772664726, 0.00151795288547873, 0.00269030313938856, 0.00214935094118118, 0.00205233669839799, 0.00211178953759372, 0.00324057880789042, 0.0016132309101522, 0.00331166782416403, 0.00152699567843229, 0.00173561275005341, 0.00183169660158455, 0.00179858156479895, 0.00233526038937271, 0.00207428960129619, 0.00285990233533084, 0.00184630113653839, 0.00178411218803376 };
  static const int16_t buff_info_Conv2D_13_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_64_32_3_3[] = { 64, 3, 3, 32 };
  static const uint32_t buff_info__mem_shape_M8_64_32_3_3[] = { 64, 4, 3, 3, 8 };
  static const float buff_info_Conv2D_19_weights_quant_scale[] = { 0.000929827685467899, 0.00182162947021425, 0.00203064759261906, 0.00251864898018539, 0.0021044984459877, 0.00258605368435383, 0.00219318922609091, 0.00202639284543693, 0.00162033434025943, 0.0014872862957418, 0.00261944299563766, 0.00262168212793767, 0.00196455768309534, 0.00146009598392993, 0.00158097606617957, 0.00271022575907409, 0.00154499872587621, 0.0010293141240254, 0.00167548190802336, 0.00179587083403021, 0.000808395096100867, 0.00198528519831598, 0.0013789456570521, 0.00164759892504662, 0.00146031787153333, 0.0013106728438288, 0.00267365900799632, 0.00183077668771148, 0.00218007969669998, 0.00255324551835656, 0.00185171794146299, 0.00209629745222628, 0.0024588864762336, 0.00216898112557828, 0.0026702203322202, 0.00250653200782835, 0.00189168949145824, 0.000742295349482447, 0.00213406304828823, 0.00110660819336772, 0.00212268764153123, 0.00213855737820268, 0.00229895301163197, 0.00261247577145696, 0.00258918688632548, 0.00164394150488079, 0.00170686258934438, 0.00225338223390281, 0.00188762252219021, 0.00187863979954273, 0.000822653295472264, 0.00148180685937405, 0.00273923063650727, 0.00255699898116291, 0.0015783216804266, 0.00161197397392243, 0.000761732400860637, 0.00264908070676029, 0.0027158388402313, 0.000755463726818562, 0.00171469629276544, 0.0026742301415652, 0.00233171787112951, 0.00162914115935564 };
  static const int16_t buff_info_Conv2D_19_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_1[] = { 1, 1, 1, 1 };
  static const uint32_t buff_info__mem_shape_U_1[] = { 1 };
  static const uint32_t buff_info__shape_32_64_1_1[] = { 32, 1, 1, 64 };
  static const uint32_t buff_info__mem_shape_F_32_64_1_1[] = { 32, 64, 1, 1 };
  static const float buff_info_Gemm_26_weights_transposed_3_quant_scale[] = { 0.0030150692909956, 0.00263835908845067, 0.00242279097437859, 0.00271472707390785, 0.00195733341388404, 0.00242666201665998, 0.00330275995656848, 0.00258275377564132, 0.00360006396658719, 0.0024078800342977, 0.00228922278620303, 0.00289293052628636, 0.00354073569178581, 0.0020752209238708, 0.00194015621673316, 0.00276836380362511, 0.00196460145525634, 0.00237961858510971, 0.00230296421796083, 0.00293163815513253, 0.00267187040299177, 0.00263987807556987, 0.00283774267882109, 0.00289070187136531, 0.00233774934895337, 0.00207857112400234, 0.00251003494486213, 0.00212744041346014, 0.0029376579914242, 0.0022464687936008, 0.00272113480605185, 0.00263704732060432 };
  static const int16_t buff_info_Gemm_26_weights_transposed_3_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_1_32_1_1[] = { 1, 1, 1, 32 };
  static const uint32_t buff_info__mem_shape_F_1_32_1_1[] = { 1, 32, 1, 1 };
  static const float buff_info_Gemm_30_weights_transposed_9_quant_scale[] = { 0.0037333897780627 };
  static const int16_t buff_info_Gemm_30_weights_transposed_9_quant_offset[] = { 0 };
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
  static const LL_Buffer_InfoTypeDef buff_info[] = {
    {
      .name = "Input_0_out_0",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 0,
      .offset_end = 37632,
      .offset_limit = 37696,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_F_1_112_112_3,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 8,
      .Qn = 0,
      .Qunsigned = 1,
      .type = DataType_UINT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_112_112_3,
      .per_channel = 0,
      .scale = buff_info_Input_0_out_0_quant_scale,
      .offset = buff_info_Input_0_out_0_quant_offset,
    },
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
    {
      .name = "Conv2D_7_weights",
      .addr_base = {(unsigned char *)(0x70400000UL) /* Equivalent hex address = 0x70400000UL */},
      .offset_start = 25104,
      .offset_end = 25536,
      .offset_limit = 25600,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 3,
      .mem_shape = buff_info__mem_shape_L_16_3_3_3,
      .mem_ndims = 4,
      .chpos = CHPos_Last,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_16_3_3_3,
      .per_channel = 1,
      .scale = buff_info_Conv2D_7_weights_quant_scale,
      .offset = buff_info_Conv2D_7_weights_quant_offset,
    },
    {
      .name = "Conv2D_13_weights",
      .addr_base = {(unsigned char *)(0x70400000UL) /* Equivalent hex address = 0x70400000UL */},
      .offset_start = 18432,
      .offset_end = 23040,
      .offset_limit = 23104,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M8_32_16_3_3,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_32_16_3_3,
      .per_channel = 1,
      .scale = buff_info_Conv2D_13_weights_quant_scale,
      .offset = buff_info_Conv2D_13_weights_quant_offset,
    },
    {
      .name = "Conv2D_19_weights",
      .addr_base = {(unsigned char *)(0x70400000UL) /* Equivalent hex address = 0x70400000UL */},
      .offset_start = 0,
      .offset_end = 18432,
      .offset_limit = 18496,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M8_64_32_3_3,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_64_32_3_3,
      .per_channel = 1,
      .scale = buff_info_Conv2D_19_weights_quant_scale,
      .offset = buff_info_Conv2D_19_weights_quant_offset,
    },
    {
      .name = "Dequantize_35_x_scale",
      .addr_base = {(unsigned char *)(0x70400000UL) /* Equivalent hex address = 0x70400000UL */},
      .offset_start = 25584,
      .offset_end = 25588,
      .offset_limit = 25656,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1,
      .mem_ndims = 1,
      .chpos = CHPos_UNDEFINED,
      .Qm = 0,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_FLOAT,
      .nbits = 32,
      .ndims = 4,
      .shape = buff_info__shape_1,
    },
    {
      .name = "Dequantize_35_x_zero_point",
      .addr_base = {(unsigned char *)(0x70400000UL) /* Equivalent hex address = 0x70400000UL */},
      .offset_start = 25600,
      .offset_end = 25601,
      .offset_limit = 25672,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1,
      .mem_ndims = 1,
      .chpos = CHPos_UNDEFINED,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1,
    },
    {
      .name = "Gemm_26_weights_transposed_3",
      .addr_base = {(unsigned char *)(0x70400000UL) /* Equivalent hex address = 0x70400000UL */},
      .offset_start = 23040,
      .offset_end = 25092,
      .offset_limit = 25160,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 64,
      .mem_shape = buff_info__mem_shape_F_32_64_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_32_64_1_1,
      .per_channel = 1,
      .scale = buff_info_Gemm_26_weights_transposed_3_quant_scale,
      .offset = buff_info_Gemm_26_weights_transposed_3_quant_offset,
    },
    {
      .name = "Gemm_30_weights_transposed_9",
      .addr_base = {(unsigned char *)(0x70400000UL) /* Equivalent hex address = 0x70400000UL */},
      .offset_start = 25536,
      .offset_end = 25569,
      .offset_limit = 25640,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 32,
      .mem_shape = buff_info__mem_shape_F_1_32_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_32_1_1,
      .per_channel = 0,
      .scale = buff_info_Gemm_30_weights_transposed_9_quant_scale,
      .offset = buff_info_Gemm_30_weights_transposed_9_quant_offset,
    },
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
    {
      .name = NULL,
    }
  };

  return buff_info;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Output_Buffers_Info_cenk(void)
{
  static const uint32_t buff_info__shape_1_1[] = { 1, 1, 1, 1 };
  static const uint32_t buff_info__mem_shape_U_1_1[] = { 1, 1 };
  static const LL_Buffer_InfoTypeDef buff_info[] = {
    {
      .name = "Dequantize_35_out_0",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 0,
      .offset_end = 4,
      .offset_limit = 72,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 8,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1_1,
      .mem_ndims = 2,
      .chpos = CHPos_UNDEFINED,
      .Qm = 0,
      .Qn = 0,
      .Qunsigned = 1,
      .type = DataType_FLOAT,
      .nbits = 32,
      .ndims = 4,
      .shape = buff_info__shape_1_1,
    },
    {
      .name = NULL,
    }
  };

  return buff_info;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Internal_Buffers_Info_cenk(void)
{
  static const uint32_t buff_info__shape_1_3_112_112[] = { 1, 112, 112, 3 };
  static const uint32_t buff_info__mem_shape_L_1_3_112_112[] = { 1, 112, 112, 3 };
  static const float buff_info_Transpose_1_out_0_quant_scale[] = { 1 };
  static const int16_t buff_info_Transpose_1_out_0_quant_offset[] = { 0 };
  static const float buff_info_Conv2D_7_zero_off_out_13_quant_scale[] = { 1 };
  static const int16_t buff_info_Conv2D_7_zero_off_out_13_quant_offset[] = { 0 };
  static const uint32_t buff_info__shape_1_16_56_56[] = { 1, 56, 56, 16 };
  static const uint32_t buff_info__mem_shape_M8_1_16_56_56[] = { 1, 2, 56, 56, 8 };
  static const float buff_info_Conv2D_13_zero_off_out_22_quant_scale[] = { 0.00588467763736844 };
  static const int16_t buff_info_Conv2D_13_zero_off_out_22_quant_offset[] = { 0 };
  static const uint32_t buff_info__shape_1_32_28_28[] = { 1, 28, 28, 32 };
  static const uint32_t buff_info__mem_shape_M8_1_32_28_28[] = { 1, 4, 28, 28, 8 };
  static const float buff_info_Conv2D_19_zero_off_out_31_quant_scale[] = { 0.00842338893562555 };
  static const int16_t buff_info_Conv2D_19_zero_off_out_31_quant_offset[] = { 0 };
  static const uint32_t buff_info__shape_1_64_1_1[] = { 1, 1, 1, 64 };
  static const uint32_t buff_info__mem_shape_F_1_64_1_1[] = { 1, 64, 1, 1 };
  static const float buff_info_Gemm_26_conv_4_zero_off_out_40_quant_scale[] = { 0.0094265341758728 };
  static const int16_t buff_info_Gemm_26_conv_4_zero_off_out_40_quant_offset[] = { 0 };
  static const uint32_t buff_info__shape_1_32_1_1[] = { 1, 1, 1, 32 };
  static const uint32_t buff_info__mem_shape_F_1_32_1_1[] = { 1, 32, 1, 1 };
  static const float buff_info_Gemm_30_conv_10_zero_off_out_49_quant_scale[] = { 0.0218193251639605 };
  static const int16_t buff_info_Gemm_30_conv_10_zero_off_out_49_quant_offset[] = { 0 };
  static const uint32_t buff_info__shape_1_1[] = { 1, 1, 1, 1 };
  static const uint32_t buff_info__mem_shape_U_1_1[] = { 1, 1 };
  static const float buff_info_Sigmoid_33_out_0_quant_scale[] = { 0.00390625 };
  static const int16_t buff_info_Sigmoid_33_out_0_quant_offset[] = { -128 };
  static const LL_Buffer_InfoTypeDef buff_info[] = {
    {
      .name = "Transpose_1_out_0",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 0,
      .offset_end = 37632,
      .offset_limit = 37696,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 1,
      .batch = 3,
      .mem_shape = buff_info__mem_shape_L_1_3_112_112,
      .mem_ndims = 4,
      .chpos = CHPos_Last,
      .Qm = 8,
      .Qn = 0,
      .Qunsigned = 1,
      .type = DataType_UINT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_3_112_112,
      .per_channel = 0,
      .scale = buff_info_Transpose_1_out_0_quant_scale,
      .offset = buff_info_Transpose_1_out_0_quant_offset,
    },
    {
      .name = "Conv2D_7_zero_off_out_13",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 50176,
      .offset_end = 87808,
      .offset_limit = 87872,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 2,
      .batch = 3,
      .mem_shape = buff_info__mem_shape_L_1_3_112_112,
      .mem_ndims = 4,
      .chpos = CHPos_Last,
      .Qm = 8,
      .Qn = 0,
      .Qunsigned = 1,
      .type = DataType_UINT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_3_112_112,
      .per_channel = 0,
      .scale = buff_info_Conv2D_7_zero_off_out_13_quant_scale,
      .offset = buff_info_Conv2D_7_zero_off_out_13_quant_offset,
    },
    {
      .name = "Conv2D_13_zero_off_out_22",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 0,
      .offset_end = 50176,
      .offset_limit = 50240,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 3,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M8_1_16_56_56,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 8,
      .Qn = 0,
      .Qunsigned = 1,
      .type = DataType_UINT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_16_56_56,
      .per_channel = 0,
      .scale = buff_info_Conv2D_13_zero_off_out_22_quant_scale,
      .offset = buff_info_Conv2D_13_zero_off_out_22_quant_offset,
    },
    {
      .name = "Conv2D_19_zero_off_out_31",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 50176,
      .offset_end = 75264,
      .offset_limit = 75328,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 4,
      .batch = 8,
      .mem_shape = buff_info__mem_shape_M8_1_32_28_28,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 8,
      .Qn = 0,
      .Qunsigned = 1,
      .type = DataType_UINT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_32_28_28,
      .per_channel = 0,
      .scale = buff_info_Conv2D_19_zero_off_out_31_quant_scale,
      .offset = buff_info_Conv2D_19_zero_off_out_31_quant_offset,
    },
    {
      .name = "Gemm_26_conv_4_zero_off_out_40",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 75264,
      .offset_end = 75328,
      .offset_limit = 75392,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 5,
      .batch = 64,
      .mem_shape = buff_info__mem_shape_F_1_64_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 8,
      .Qn = 0,
      .Qunsigned = 1,
      .type = DataType_UINT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_64_1_1,
      .per_channel = 0,
      .scale = buff_info_Gemm_26_conv_4_zero_off_out_40_quant_scale,
      .offset = buff_info_Gemm_26_conv_4_zero_off_out_40_quant_offset,
    },
    {
      .name = "Gemm_30_conv_10_zero_off_out_49",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 75328,
      .offset_end = 75360,
      .offset_limit = 75424,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 6,
      .batch = 32,
      .mem_shape = buff_info__mem_shape_F_1_32_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 8,
      .Qn = 0,
      .Qunsigned = 1,
      .type = DataType_UINT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_32_1_1,
      .per_channel = 0,
      .scale = buff_info_Gemm_30_conv_10_zero_off_out_49_quant_scale,
      .offset = buff_info_Gemm_30_conv_10_zero_off_out_49_quant_offset,
    },
    {
      .name = "Sigmoid_33_out_0",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 75360,
      .offset_end = 75361,
      .offset_limit = 75432,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 7,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1_1,
      .mem_ndims = 2,
      .chpos = CHPos_UNDEFINED,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_1,
      .per_channel = 0,
      .scale = buff_info_Sigmoid_33_out_0_quant_scale,
      .offset = buff_info_Sigmoid_33_out_0_quant_offset,
    },
    {
      .name = NULL,
    }
  };

  return buff_info;
}

