
/* AUTOGENERATED DO NOT MODIFY */

/**
 ******************************************************************************
 * @file    stai_cenk.h
 * @author  SRA Artificial Intelligence & Embedded Architectures
 * @brief   Implementation of ST.AI platform public APIs for ATON
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#ifndef __STAI_ATON_CENK_H
#define __STAI_ATON_CENK_H

// Include ATON runtime/library configuration file
#include "ll_aton_config.h"
#include "ll_aton_stai_internal.h"

// clang-format off
#ifdef __cplusplus
extern "C"
{
#endif

/*
 * NOTE: the beyond macro MUST be set to the same value when compiling the different ATON runtime/library, and
 *       AtoNN compiler generated files
 */
#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

// Derive alignment
#define _alignof(t)                                                                                                    \
  ((sizeof(t) > 1) ? offsetof(                                                                                         \
                         struct {                                                                                      \
                           char c;                                                                                     \
                           t x;                                                                                        \
                         },                                                                                            \
                         x)                                                                                            \
                   : 1)

// Include ST.AI headers
#include "stai_aton_common.h"

/*****************************************************************************/
#define STAI_CENK_CONTEXT_SIZE      ((stai_size)sizeof(_stai_aton_context))
#define STAI_CENK_CONTEXT_ALIGNMENT (_alignof(_stai_aton_context))

/*****************************************************************************/
STAI_API_DECLARE_BEGIN

/*****************************************************************************/
/* ST.AI API extensions are available */
#ifndef HAS_STAI_EXT
#define HAS_STAI_EXT
#endif // HAS_STAI_EXT

/*****************************************************************************/
/*  Network management APIs  */
STAI_API_ENTRY
stai_return_code stai_cenk_init(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_cenk_deinit(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_cenk_run(stai_network *network, const stai_run_mode mode);

STAI_API_ENTRY
stai_return_code stai_cenk_train(stai_network *network, const stai_run_mode mode);

/*****************************************************************************/
/*  Getters APIs  */

// needed only for python bindings to query internal context byte size
STAI_API_ENTRY
static inline stai_size stai_cenk_get_context_size(void)
{
  return STAI_CENK_CONTEXT_SIZE;
}

STAI_API_ENTRY
stai_return_code stai_cenk_get_info(stai_network *network, stai_network_info *info);

STAI_API_ENTRY
stai_return_code stai_cenk_get_inputs(stai_network *network, stai_ptr *inputs, stai_size *n_inputs);

STAI_API_ENTRY
stai_return_code stai_cenk_get_weights(stai_network *network, stai_ptr *weights, stai_size *n_weights);

STAI_API_ENTRY
stai_return_code stai_cenk_get_outputs(stai_network *network, stai_ptr *outputs, stai_size *n_outputs);

STAI_API_ENTRY
stai_return_code stai_cenk_get_activations(stai_network *network, stai_ptr *activations,
                                                            stai_size *n_activations);

STAI_API_ENTRY
stai_return_code stai_cenk_get_states(stai_network *network, stai_ptr *states, stai_size *n_states);
STAI_API_ENTRY
stai_return_code stai_cenk_get_error(stai_network *network);

/*****************************************************************************/
/*  Setters APIs  */

/**
 * @brief Set array of input buffers
 * @param network NN for which to set the input buffers
 * @param inputs array of input buffer pointers
 * @param n_inputs number of elements in the input buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_cenk_set_inputs(stai_network *network, const stai_ptr *inputs,
                                                       const stai_size n_inputs);

/**
 * @brief Set array of weight buffers
 * @param network NN for which to set the weight buffers
 * @param weights array of weight buffer pointers
 * @param n_weights number of elements in the weight buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for weights
 */
STAI_API_ENTRY
stai_return_code stai_cenk_set_weights(stai_network *network, const stai_ptr *weights,
                                                        const stai_size n_weights);

/**
 * @brief Set array of output buffers
 * @param network NN for which to set the output buffers
 * @param outputs array of output buffer pointers
 * @param n_outputs number of elements in the output buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_cenk_set_outputs(stai_network *network, const stai_ptr *outputs,
                                                        const stai_size n_outputs);

/**
 * @brief Set array of activation buffers
 * @param network NN for which to set the activation buffers
 * @param activations array of activation buffer pointers
 * @param n_activations number of elements in the activation buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for activations
 */
STAI_API_ENTRY
stai_return_code stai_cenk_set_activations(stai_network *network, const stai_ptr *activations,
                                                            const stai_size n_activations);

STAI_API_ENTRY
stai_return_code stai_cenk_set_states(stai_network *network, const stai_ptr *states,
                                                       const stai_size n_states);

STAI_API_ENTRY
stai_return_code stai_cenk_set_callback(stai_network *network, const stai_event_cb cb,
                                                         void *cb_cookie);

/***************************************************************************/
/*  Extended ATON Target Specific APIs  */

/** Asynchronous Execution **/
/**
 * @brief Continue network execution of an asynchronously started/run network
 *        (i.e. network was started/run in `stai_run_mode::STAI_MODE_ASYNC` mode)
 * @details Running a network in asynchronous mode (see function `stai_cenk_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_cenk_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_cenk_run()` again until the network's execution has
 *          actually finished.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_cenk_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_cenk_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_cenk_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_cenk_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_cenk_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_cenk_run_continue()`
 * again)
 * @param[in] network network opaque pointer
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_cenk_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_cenk_run_continue(stai_network *network);

/**
 * @brief Get execution status of a network
 * @details Running a network in asynchronous mode (see function `stai_cenk_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_cenk_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_cenk_run()` again until the network's execution has
 *          actually finish.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_cenk_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_cenk_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_cenk_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_cenk_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_cenk_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_cenk_run_continue()`
 * again)
 * @param[in] network network handle
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_cenk_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_cenk_get_nn_run_status(stai_network *network);

/**
 * @brief Prepare the network for a new inference
 * @details In case `stai_ext_cenk_get_nn_run_status()` returns either `STAI_DONE` or
 *          `STAI_RUNNING_NO_WFE` (when called by the thread which actually executes the inference of the passed
 *          `network`), prepare `network` for another/new inference run.
 * @param[in] network network handle
 * @return
 *
 * @note May only be called by the thread actually executing the inference of `network`!
 * @note Necessary only in case current inference is/has been executed asynchronously!
 */
STAI_API_ENTRY
stai_return_code stai_ext_cenk_new_inference(stai_network *network);

/*****************************************************************************/
STAI_API_DECLARE_END

/*****************************************************************************/
#define STAI_CENK_STATES_NUM  (0)
#define STAI_CENK_STATES_SIZE (0)

/*****************************************************************************/
/************************** SUBSTITUTABLE section ****************************/
/*****************************************************************************/

/**************************** Cache line size(s) *****************************/
#ifndef STAI_CACHE_MCU_LINESIZE
#define STAI_CACHE_MCU_LINESIZE (32)
#elif (STAI_CACHE_MCU_LINESIZE != 32)
#error "MCU cache line size mismatch"
#endif

/* NPU cache extension is available */
#ifndef STAI_EXT_CACHE_HAS_NPU
#define STAI_EXT_CACHE_HAS_NPU
#endif
#define STAI_CENK_EXT_CACHE_HAS_NPU

#ifndef STAI_EXT_CACHE_NPU_LINESIZE
#define STAI_EXT_CACHE_NPU_LINESIZE (64)
#elif (STAI_EXT_CACHE_NPU_LINESIZE != 64)
#error "NPU cache line size mismatch"
#endif

#ifndef STAI_CACHE_USER_BUFFER_ALIGNMENT
#define STAI_CACHE_USER_BUFFER_ALIGNMENT STAI_CACHE_MCU_LINESIZE  // NOTE: user allocated buffers are assumed not to be NPU cacheable!
#endif

/********************************** INPUTS ***********************************/
#define STAI_CENK_IN_NUM (1)
#define STAI_CENK_IN_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_CENK_IN_NAMES \
  { \
    "Input_0_out_0" \
  }
#define STAI_CENK_IN_FORMATS \
  { \
    STAI_FORMAT_U8 \
  }
#define STAI_CENK_IN_SIZES \
  { \
    37632 \
  }
#define STAI_CENK_IN_SIZES_BYTES \
  { \
    37632 \
  }

#define STAI_CENK_IN_1_ALIGNMENT (32)
#define STAI_CENK_IN_1_NAME "Input_0_out_0"
#define STAI_CENK_IN_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_CENK_IN_1_FORMAT (STAI_FORMAT_U8)
#define STAI_CENK_IN_1_SIZE (37632)
#define STAI_CENK_IN_1_SIZE_BYTES (37632)
#define STAI_CENK_IN_1_CHANNEL (3)
#define STAI_CENK_IN_1_HEIGHT (112)
#define STAI_CENK_IN_1_WIDTH (112)
#define STAI_CENK_IN_1_BATCH (1)
#define STAI_CENK_IN_1_RANK (4)
#define STAI_CENK_IN_1_SHAPE \
  { \
    1, 112, 112, 3 \
  }
#define STAI_CENK_IN_1_SCALE_OFFSET_NUM (1)
#define STAI_CENK_IN_1_SCALES \
  { \
    1 \
  }
#define STAI_CENK_IN_1_OFFSETS \
  { \
    0 \
  }

/********************************** OUTPUTS **********************************/
#define STAI_CENK_OUT_NUM (1)
#define STAI_CENK_OUT_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_CENK_OUT_NAMES \
  { \
    "Quantize_36_out_0" \
  }
#define STAI_CENK_OUT_FORMATS \
  { \
    STAI_FORMAT_U8 \
  }
#define STAI_CENK_OUT_SIZES \
  { \
    1 \
  }
#define STAI_CENK_OUT_SIZES_BYTES \
  { \
    1 \
  }

#define STAI_CENK_OUT_1_ALIGNMENT (32)
#define STAI_CENK_OUT_1_NAME "Quantize_36_out_0"
#define STAI_CENK_OUT_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE)
#define STAI_CENK_OUT_1_FORMAT (STAI_FORMAT_U8)
#define STAI_CENK_OUT_1_SIZE (1)
#define STAI_CENK_OUT_1_SIZE_BYTES (1)
#define STAI_CENK_OUT_1_CHANNEL (1)
#define STAI_CENK_OUT_1_HEIGHT (1)
#define STAI_CENK_OUT_1_WIDTH (1)
#define STAI_CENK_OUT_1_RANK (2)
#define STAI_CENK_OUT_1_SHAPE \
  { \
    1, 1 \
  }
#define STAI_CENK_OUT_1_SCALE_OFFSET_NUM (1)
#define STAI_CENK_OUT_1_SCALES \
  { \
    0.00390625 \
  }
#define STAI_CENK_OUT_1_OFFSETS \
  { \
    0 \
  }

/********************************** WEIGHTS **********************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_CENK_WEIGHTS_NUM (5)
#define STAI_CENK_WEIGHTS_ALIGNMENTS \
  { \
    16, 32, 32, 32, 32 \
  }
#define STAI_CENK_WEIGHTS_NAMES \
  { \
    "Conv2D_7_weights", "Conv2D_13_weights", "Conv2D_19_weights", "Gemm_26_weights_transposed_3", "Gemm_30_weights_transposed_9" \
  }
#define STAI_CENK_WEIGHTS_FORMATS \
  { \
    STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8 \
  }
#define STAI_CENK_WEIGHTS_SIZES \
  { \
    432, 4608, 18432, 2048, 32 \
  }
#define STAI_CENK_WEIGHTS_SIZES_BYTES \
  { \
    432, 4608, 18432, 2048, 32 \
  }

#define STAI_CENK_WEIGHTS_1_ALIGNMENT (16)
#define STAI_CENK_WEIGHTS_1_NAME "Conv2D_7_weights"
#define STAI_CENK_WEIGHTS_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_CENK_WEIGHTS_1_FORMAT (STAI_FORMAT_S8)
#define STAI_CENK_WEIGHTS_1_SIZE (432)
#define STAI_CENK_WEIGHTS_1_SIZE_BYTES (432)
#define STAI_CENK_WEIGHTS_1_CHANNEL (3)
#define STAI_CENK_WEIGHTS_1_HEIGHT (3)
#define STAI_CENK_WEIGHTS_1_WIDTH (3)
#define STAI_CENK_WEIGHTS_1_BATCH (3)
#define STAI_CENK_WEIGHTS_1_RANK (4)
#define STAI_CENK_WEIGHTS_1_SHAPE \
  { \
    16, 3, 3, 3 \
  }
#define STAI_CENK_WEIGHTS_1_SCALE_OFFSET_NUM (16)
#define STAI_CENK_WEIGHTS_1_SCALES \
  { \
    7.20927891961765e-06, 6.61777085042559e-06, 5.99253053223947e-06, 9.4148581410991e-06, 5.14917974214768e-06, 6.05505692874431e-06, 6.26388600721839e-06, 5.75314197703847e-06, 9.03492400539108e-06, 6.46077342025819e-06, 6.60474370306474e-06, 5.49613287148532e-06, 5.50784534425475e-06, 6.65459765514242e-06, 6.04671458859229e-06, 5.90757781537832e-06 \
  }
#define STAI_CENK_WEIGHTS_1_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_CENK_WEIGHTS_2_ALIGNMENT (32)
#define STAI_CENK_WEIGHTS_2_NAME "Conv2D_13_weights"
#define STAI_CENK_WEIGHTS_2_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_CENK_WEIGHTS_2_FORMAT (STAI_FORMAT_S8)
#define STAI_CENK_WEIGHTS_2_SIZE (4608)
#define STAI_CENK_WEIGHTS_2_SIZE_BYTES (4608)
#define STAI_CENK_WEIGHTS_2_CHANNEL (16)
#define STAI_CENK_WEIGHTS_2_HEIGHT (3)
#define STAI_CENK_WEIGHTS_2_WIDTH (3)
#define STAI_CENK_WEIGHTS_2_BATCH (8)
#define STAI_CENK_WEIGHTS_2_RANK (5)
#define STAI_CENK_WEIGHTS_2_SHAPE \
  { \
    32, 2, 3, 3, 8 \
  }
#define STAI_CENK_WEIGHTS_2_SCALE_OFFSET_NUM (32)
#define STAI_CENK_WEIGHTS_2_SCALES \
  { \
    0.00340545317158103, 0.00207994366064668, 0.00125253957230598, 0.00369354547001421, 0.00197179964743555, 0.00210126489400864, 0.00150797353126109, 0.00196072109974921, 0.00183571700472385, 0.00227534840814769, 0.00276370951905847, 0.0020777159370482, 0.00258423248305917, 0.00147059408482164, 0.00215832772664726, 0.00151795288547873, 0.00269030313938856, 0.00214935094118118, 0.00205233669839799, 0.00211178953759372, 0.00324057880789042, 0.0016132309101522, 0.00331166782416403, 0.00152699567843229, 0.00173561275005341, 0.00183169660158455, 0.00179858156479895, 0.00233526038937271, 0.00207428960129619, 0.00285990233533084, 0.00184630113653839, 0.00178411218803376 \
  }
#define STAI_CENK_WEIGHTS_2_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_CENK_WEIGHTS_3_ALIGNMENT (32)
#define STAI_CENK_WEIGHTS_3_NAME "Conv2D_19_weights"
#define STAI_CENK_WEIGHTS_3_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_CENK_WEIGHTS_3_FORMAT (STAI_FORMAT_S8)
#define STAI_CENK_WEIGHTS_3_SIZE (18432)
#define STAI_CENK_WEIGHTS_3_SIZE_BYTES (18432)
#define STAI_CENK_WEIGHTS_3_CHANNEL (32)
#define STAI_CENK_WEIGHTS_3_HEIGHT (3)
#define STAI_CENK_WEIGHTS_3_WIDTH (3)
#define STAI_CENK_WEIGHTS_3_BATCH (8)
#define STAI_CENK_WEIGHTS_3_RANK (5)
#define STAI_CENK_WEIGHTS_3_SHAPE \
  { \
    64, 4, 3, 3, 8 \
  }
#define STAI_CENK_WEIGHTS_3_SCALE_OFFSET_NUM (64)
#define STAI_CENK_WEIGHTS_3_SCALES \
  { \
    0.000929827685467899, 0.00182162947021425, 0.00203064759261906, 0.00251864898018539, 0.0021044984459877, 0.00258605368435383, 0.00219318922609091, 0.00202639284543693, 0.00162033434025943, 0.0014872862957418, 0.00261944299563766, 0.00262168212793767, 0.00196455768309534, 0.00146009598392993, 0.00158097606617957, 0.00271022575907409, 0.00154499872587621, 0.0010293141240254, 0.00167548190802336, 0.00179587083403021, 0.000808395096100867, 0.00198528519831598, 0.0013789456570521, 0.00164759892504662, 0.00146031787153333, 0.0013106728438288, 0.00267365900799632, 0.00183077668771148, 0.00218007969669998, 0.00255324551835656, 0.00185171794146299, 0.00209629745222628, 0.0024588864762336, 0.00216898112557828, 0.0026702203322202, 0.00250653200782835, 0.00189168949145824, 0.000742295349482447, 0.00213406304828823, 0.00110660819336772, 0.00212268764153123, 0.00213855737820268, 0.00229895301163197, 0.00261247577145696, 0.00258918688632548, 0.00164394150488079, 0.00170686258934438, 0.00225338223390281, 0.00188762252219021, 0.00187863979954273, 0.000822653295472264, 0.00148180685937405, 0.00273923063650727, 0.00255699898116291, 0.0015783216804266, 0.00161197397392243, 0.000761732400860637, 0.00264908070676029, 0.0027158388402313, 0.000755463726818562, 0.00171469629276544, 0.0026742301415652, 0.00233171787112951, 0.00162914115935564 \
  }
#define STAI_CENK_WEIGHTS_3_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_CENK_WEIGHTS_4_ALIGNMENT (32)
#define STAI_CENK_WEIGHTS_4_NAME "Gemm_26_weights_transposed_3"
#define STAI_CENK_WEIGHTS_4_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_CENK_WEIGHTS_4_FORMAT (STAI_FORMAT_S8)
#define STAI_CENK_WEIGHTS_4_SIZE (2048)
#define STAI_CENK_WEIGHTS_4_SIZE_BYTES (2048)
#define STAI_CENK_WEIGHTS_4_CHANNEL (64)
#define STAI_CENK_WEIGHTS_4_HEIGHT (1)
#define STAI_CENK_WEIGHTS_4_WIDTH (1)
#define STAI_CENK_WEIGHTS_4_BATCH (64)
#define STAI_CENK_WEIGHTS_4_RANK (4)
#define STAI_CENK_WEIGHTS_4_SHAPE \
  { \
    32, 1, 1, 64 \
  }
#define STAI_CENK_WEIGHTS_4_SCALE_OFFSET_NUM (32)
#define STAI_CENK_WEIGHTS_4_SCALES \
  { \
    0.0030150692909956, 0.00263835908845067, 0.00242279097437859, 0.00271472707390785, 0.00195733341388404, 0.00242666201665998, 0.00330275995656848, 0.00258275377564132, 0.00360006396658719, 0.0024078800342977, 0.00228922278620303, 0.00289293052628636, 0.00354073569178581, 0.0020752209238708, 0.00194015621673316, 0.00276836380362511, 0.00196460145525634, 0.00237961858510971, 0.00230296421796083, 0.00293163815513253, 0.00267187040299177, 0.00263987807556987, 0.00283774267882109, 0.00289070187136531, 0.00233774934895337, 0.00207857112400234, 0.00251003494486213, 0.00212744041346014, 0.0029376579914242, 0.0022464687936008, 0.00272113480605185, 0.00263704732060432 \
  }
#define STAI_CENK_WEIGHTS_4_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_CENK_WEIGHTS_5_ALIGNMENT (32)
#define STAI_CENK_WEIGHTS_5_NAME "Gemm_30_weights_transposed_9"
#define STAI_CENK_WEIGHTS_5_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_CENK_WEIGHTS_5_FORMAT (STAI_FORMAT_S8)
#define STAI_CENK_WEIGHTS_5_SIZE (32)
#define STAI_CENK_WEIGHTS_5_SIZE_BYTES (32)
#define STAI_CENK_WEIGHTS_5_CHANNEL (32)
#define STAI_CENK_WEIGHTS_5_HEIGHT (1)
#define STAI_CENK_WEIGHTS_5_WIDTH (1)
#define STAI_CENK_WEIGHTS_5_BATCH (32)
#define STAI_CENK_WEIGHTS_5_RANK (4)
#define STAI_CENK_WEIGHTS_5_SHAPE \
  { \
    1, 1, 1, 32 \
  }
#define STAI_CENK_WEIGHTS_5_SCALE_OFFSET_NUM (1)
#define STAI_CENK_WEIGHTS_5_SCALES \
  { \
    0.0037333897780627 \
  }
#define STAI_CENK_WEIGHTS_5_OFFSETS \
  { \
    0 \
  }
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_CENK_WEIGHTS_NUM (0)
#define STAI_CENK_WEIGHTS_ALIGNMENTS \
  { \
  }
#define STAI_CENK_WEIGHTS_NAMES \
  { \
  }
#define STAI_CENK_WEIGHTS_FORMATS \
  { \
  }
#define STAI_CENK_WEIGHTS_SIZES \
  { \
  }
#define STAI_CENK_WEIGHTS_SIZES_BYTES \
  { \
  }
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0

/******************************** ACTIVATIONS ********************************/
#define STAI_CENK_ACTIVATIONS_NUM (6)
#define STAI_CENK_ACTIVATIONS_ALIGNMENTS \
  { \
    32, 32, 32, 32, 32, 32 \
  }
#define STAI_CENK_ACTIVATIONS_NAMES \
  { \
    "Transpose_1_out_0", "Conv2D_7_zero_off_out_13", "Conv2D_13_zero_off_out_22", "Conv2D_19_zero_off_out_31", "Gemm_26_conv_4_zero_off_out_40", "Gemm_30_conv_10_zero_off_out_49" \
  }
#define STAI_CENK_ACTIVATIONS_FORMATS \
  { \
    STAI_FORMAT_U8, STAI_FORMAT_U8, STAI_FORMAT_U8, STAI_FORMAT_U8, STAI_FORMAT_U8, STAI_FORMAT_U8 \
  }
#define STAI_CENK_ACTIVATIONS_SIZES \
  { \
    37632, 37632, 50176, 25088, 64, 32 \
  }
#define STAI_CENK_ACTIVATIONS_SIZES_BYTES \
  { \
    37632, 37632, 50176, 25088, 64, 32 \
  }

#define STAI_CENK_ACTIVATIONS_1_ALIGNMENT (32)
#define STAI_CENK_ACTIVATIONS_1_NAME "Transpose_1_out_0"
#define STAI_CENK_ACTIVATIONS_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_CENK_ACTIVATIONS_1_FORMAT (STAI_FORMAT_U8)
#define STAI_CENK_ACTIVATIONS_1_SIZE (37632)
#define STAI_CENK_ACTIVATIONS_1_SIZE_BYTES (37632)
#define STAI_CENK_ACTIVATIONS_1_CHANNEL (3)
#define STAI_CENK_ACTIVATIONS_1_HEIGHT (112)
#define STAI_CENK_ACTIVATIONS_1_WIDTH (112)
#define STAI_CENK_ACTIVATIONS_1_BATCH (3)
#define STAI_CENK_ACTIVATIONS_1_RANK (4)
#define STAI_CENK_ACTIVATIONS_1_SHAPE \
  { \
    1, 112, 112, 3 \
  }
#define STAI_CENK_ACTIVATIONS_1_SCALE_OFFSET_NUM (1)
#define STAI_CENK_ACTIVATIONS_1_SCALES \
  { \
    1 \
  }
#define STAI_CENK_ACTIVATIONS_1_OFFSETS \
  { \
    0 \
  }

#define STAI_CENK_ACTIVATIONS_2_ALIGNMENT (32)
#define STAI_CENK_ACTIVATIONS_2_NAME "Conv2D_7_zero_off_out_13"
#define STAI_CENK_ACTIVATIONS_2_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_CENK_ACTIVATIONS_2_FORMAT (STAI_FORMAT_U8)
#define STAI_CENK_ACTIVATIONS_2_SIZE (37632)
#define STAI_CENK_ACTIVATIONS_2_SIZE_BYTES (37632)
#define STAI_CENK_ACTIVATIONS_2_CHANNEL (3)
#define STAI_CENK_ACTIVATIONS_2_HEIGHT (112)
#define STAI_CENK_ACTIVATIONS_2_WIDTH (112)
#define STAI_CENK_ACTIVATIONS_2_BATCH (3)
#define STAI_CENK_ACTIVATIONS_2_RANK (4)
#define STAI_CENK_ACTIVATIONS_2_SHAPE \
  { \
    1, 112, 112, 3 \
  }
#define STAI_CENK_ACTIVATIONS_2_SCALE_OFFSET_NUM (1)
#define STAI_CENK_ACTIVATIONS_2_SCALES \
  { \
    1 \
  }
#define STAI_CENK_ACTIVATIONS_2_OFFSETS \
  { \
    0 \
  }

#define STAI_CENK_ACTIVATIONS_3_ALIGNMENT (32)
#define STAI_CENK_ACTIVATIONS_3_NAME "Conv2D_13_zero_off_out_22"
#define STAI_CENK_ACTIVATIONS_3_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_HAS_BATCH)
#define STAI_CENK_ACTIVATIONS_3_FORMAT (STAI_FORMAT_U8)
#define STAI_CENK_ACTIVATIONS_3_SIZE (50176)
#define STAI_CENK_ACTIVATIONS_3_SIZE_BYTES (50176)
#define STAI_CENK_ACTIVATIONS_3_CHANNEL (16)
#define STAI_CENK_ACTIVATIONS_3_HEIGHT (56)
#define STAI_CENK_ACTIVATIONS_3_WIDTH (56)
#define STAI_CENK_ACTIVATIONS_3_BATCH (8)
#define STAI_CENK_ACTIVATIONS_3_RANK (5)
#define STAI_CENK_ACTIVATIONS_3_SHAPE \
  { \
    1, 2, 56, 56, 8 \
  }
#define STAI_CENK_ACTIVATIONS_3_SCALE_OFFSET_NUM (1)
#define STAI_CENK_ACTIVATIONS_3_SCALES \
  { \
    0.00588467763736844 \
  }
#define STAI_CENK_ACTIVATIONS_3_OFFSETS \
  { \
    0 \
  }

#define STAI_CENK_ACTIVATIONS_4_ALIGNMENT (32)
#define STAI_CENK_ACTIVATIONS_4_NAME "Conv2D_19_zero_off_out_31"
#define STAI_CENK_ACTIVATIONS_4_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_HAS_BATCH)
#define STAI_CENK_ACTIVATIONS_4_FORMAT (STAI_FORMAT_U8)
#define STAI_CENK_ACTIVATIONS_4_SIZE (25088)
#define STAI_CENK_ACTIVATIONS_4_SIZE_BYTES (25088)
#define STAI_CENK_ACTIVATIONS_4_CHANNEL (32)
#define STAI_CENK_ACTIVATIONS_4_HEIGHT (28)
#define STAI_CENK_ACTIVATIONS_4_WIDTH (28)
#define STAI_CENK_ACTIVATIONS_4_BATCH (8)
#define STAI_CENK_ACTIVATIONS_4_RANK (5)
#define STAI_CENK_ACTIVATIONS_4_SHAPE \
  { \
    1, 4, 28, 28, 8 \
  }
#define STAI_CENK_ACTIVATIONS_4_SCALE_OFFSET_NUM (1)
#define STAI_CENK_ACTIVATIONS_4_SCALES \
  { \
    0.00842338893562555 \
  }
#define STAI_CENK_ACTIVATIONS_4_OFFSETS \
  { \
    0 \
  }

#define STAI_CENK_ACTIVATIONS_5_ALIGNMENT (32)
#define STAI_CENK_ACTIVATIONS_5_NAME "Gemm_26_conv_4_zero_off_out_40"
#define STAI_CENK_ACTIVATIONS_5_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_CENK_ACTIVATIONS_5_FORMAT (STAI_FORMAT_U8)
#define STAI_CENK_ACTIVATIONS_5_SIZE (64)
#define STAI_CENK_ACTIVATIONS_5_SIZE_BYTES (64)
#define STAI_CENK_ACTIVATIONS_5_CHANNEL (64)
#define STAI_CENK_ACTIVATIONS_5_HEIGHT (1)
#define STAI_CENK_ACTIVATIONS_5_WIDTH (1)
#define STAI_CENK_ACTIVATIONS_5_BATCH (64)
#define STAI_CENK_ACTIVATIONS_5_RANK (4)
#define STAI_CENK_ACTIVATIONS_5_SHAPE \
  { \
    1, 1, 1, 64 \
  }
#define STAI_CENK_ACTIVATIONS_5_SCALE_OFFSET_NUM (1)
#define STAI_CENK_ACTIVATIONS_5_SCALES \
  { \
    0.0094265341758728 \
  }
#define STAI_CENK_ACTIVATIONS_5_OFFSETS \
  { \
    0 \
  }

#define STAI_CENK_ACTIVATIONS_6_ALIGNMENT (32)
#define STAI_CENK_ACTIVATIONS_6_NAME "Gemm_30_conv_10_zero_off_out_49"
#define STAI_CENK_ACTIVATIONS_6_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_CENK_ACTIVATIONS_6_FORMAT (STAI_FORMAT_U8)
#define STAI_CENK_ACTIVATIONS_6_SIZE (32)
#define STAI_CENK_ACTIVATIONS_6_SIZE_BYTES (32)
#define STAI_CENK_ACTIVATIONS_6_CHANNEL (32)
#define STAI_CENK_ACTIVATIONS_6_HEIGHT (1)
#define STAI_CENK_ACTIVATIONS_6_WIDTH (1)
#define STAI_CENK_ACTIVATIONS_6_BATCH (32)
#define STAI_CENK_ACTIVATIONS_6_RANK (4)
#define STAI_CENK_ACTIVATIONS_6_SHAPE \
  { \
    1, 1, 1, 32 \
  }
#define STAI_CENK_ACTIVATIONS_6_SCALE_OFFSET_NUM (1)
#define STAI_CENK_ACTIVATIONS_6_SCALES \
  { \
    0.0218193251639605 \
  }
#define STAI_CENK_ACTIVATIONS_6_OFFSETS \
  { \
    0 \
  }

/****************************** NETWORK MACROS *******************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_CENK_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS|STAI_FLAG_ACTIVATIONS)
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_CENK_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS|STAI_FLAG_ACTIVATIONS|STAI_FLAG_WEIGHTS)
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0

#define STAI_CENK_ORIGIN_MODEL_NAME "cenk_classifier_int8_OE_3_3_1"
#define STAI_CENK_C_MODEL_NAME "cenk"

/*************************** RELATIVE MEMORY POOLS ***************************/
/* no memory pools with relative addresses */

#ifdef __cplusplus
}
#endif

#endif // __STAI_ATON_CENK_H
